[package]
name = "quantum"
version = "0.1.0"
authors = ["Shuyang Sun <sunbuffett@gmail.com>"]
edition = "2018"

[dependencies]
num = "0.2.1"
alga = "0.9.3"
num-complex = "0.2.4"
nalgebra = "0.21.0"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
lto = true
